### ISSUE TITLE
Spanner: We may not be retrying requests when WithSessionExpiryChecking() fails with UNAVAILABLE

### ISSUE THREAD

**Issue by skuruppu** [googleapis/google-cloud-dotnet#5977]
We got a customer issue reported where they are using the `SpannerDataReader` and they see an error in their logs:

```
Exception details: google.Cloud.Spanner.Data.SpannerException: The service is currently unavailable. This is a most likely a transient condition.

---> Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="GOAWAY received", DebugException="Grpc.Core.Internal.CoreErrorDetailException:
```

There doesn't seem to be any impact on the workload from this error other than it taking a long time when this happens. Looking at the code, an UNAVAILABLE error is [caught](https://github.com/googleapis/google-cloud-dotnet/blob/master/apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/SqlResultStream.cs#L182) and [retried](https://github.com/googleapis/google-cloud-dotnet/blob/master/apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/SqlResultStream.cs#L244). But that's only if [`hasNext`](https://github.com/googleapis/google-cloud-dotnet/blob/13a903abdc395fcdb8c22dbe0434a1fa0288cf8e/apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/SqlResultStream.cs#L140) is computed and [`_safeToRetry`](https://github.com/googleapis/google-cloud-dotnet/blob/13a903abdc395fcdb8c22dbe0434a1fa0288cf8e/apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/SqlResultStream.cs#L154) is set.

I don't think it's getting this far based on the below stack trace because I see [`WithExpirationChecking()`](https://github.com/googleapis/google-cloud-dotnet/blob/master/apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/SqlResultStream.cs#L142).

![BSPLuxw3GsCLTMD](https://user-images.githubusercontent.com/951152/109082280-c40d5400-7757-11eb-809c-3706129aebd1.png)

My question is will the RPC be retried elsewhere even if the `UNAVAILBLE` error is not caught in this loop?

CC @olavloite

**Comment by skuruppu** [comment]
Maybe we need to implement similar logic to that of [Node.js](https://github.com/googleapis/nodejs-spanner/issues/620#issuecomment-573048988) that @olavloite worked on a few months ago.

**Comment by jskeet** [comment]
I'll try to take a look today.

**Comment by jskeet** [comment]
No, if the RPC isn't retried there, I don't *think* there's anywhere else it would be retried. I don't think anything else would have enough information *to* retry it sensibly. Note that retrying streaming RPCs is inherently somewhat different to retrying regular ones.

I don't think this has anything to do with `WithSessionExpiryChecking` though - the *only* impact of that method should be to mark the session expired if the exception is "Session not found" (which it isn't in this case). All exceptions are just passed through, so it shouldn't affect retry at all.

This exception propagating suggests that either:

- We received more than 512 partial result sets since the last resume token (so we no longer have a valid resume token) and then an error occurred
- Two RPCs failed in a row

The first of these is complicated to go through - I'd need to look much more closely at the code. It seems much more likely that we've received two RPC failures in a row, despite backing off for as long as the first RPC said we ought to.

The part about `hasNext` is a red herring, I believe - `_safeToRetry` starts off as `true`. So even if the very first request fails, we'll still retry - but if that *second* request fails as well, that won't be retried.

**Comment by skuruppu** [comment]
Thanks @jskeet, that makes sense. I missed the fact that `_safeToRetry` is `true` to begin with.

I think you're right that it's way more likely that they received two failures in a row.

I will mark this as closed since there's no action we can take. I might reopen it if more information comes up.

**Comment by skuruppu** [comment]
@olavloite did some investigations and he was able to reproduce the issue with two consecutive UNAVAILABLE errors being returned.

From his experience no other Spanner client libraries has this restriction. His recommendation was to remove `_maxConsecutiveErrors` and retry until the total timeout is reached.

@jskeet, is there a reason that the C# client chose this path? Do you see any problems with changing this logic?

This issue is still impacting the customer.

**Comment by jskeet** [comment]
@skuruppu: I suspect when I implemented SqlResultStream, I was *either* taking my cue from the Java code at the time (which may well have changed since then) *or* from the .NET code at the time (which we were fixing, basically).

I think if we retry until the total timeout is reached, we should probably add some sort of minimum sleep time in there. At the moment, if the failure doesn't indicate how long to wait for, we don't wait at all - which could lead to us basically hammering a failed node (or whatever) as hard as we could. The "max consecutive errors" prevents that, so if we remove that protection we should add something else in.

**Comment by skuruppu** [comment]
Ah ok, so I was thinking we'll implement it with exp backoff so that should address your concern.

@olavloite would you be able to take this on? For some reason, I still can't assign you issues.

**Comment by skuruppu** [comment]
Ah figured it out!
